"""
Django settings for tetris project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import django_heroku
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4zd0fb*h#vvn*os*ir&@*w8rg0f77)x^frr$p2hruqypv9t9y*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# damp-wave-85305
# ALLOWED_HOSTS = ['localhost','127.0.0.1','https://cs252tetris.herokuapp.com/', 'https://damp-wave-85305.herokuapp.com/']

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'channels',
	'Tetris',
	'Main',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tetris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tetris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DATABASES = {
    'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'tetris',
		'USER': 'root',
		'PASSWORD': 'hello',
		'HOST': '127.0.0.1',
		'PORT': '3306',
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': ''
    }
}
"""


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

TEMPLATES_DIRS = (
	os.path.join(os.path.dirname(__file__), 'templates')
)

ASGI_APPLICATION = 'Tetris.routing.application'
# ASGI_APPLICATION = 'routing.application'

# "BACKEND": "asgi_redis.core.RedisChannelLayer",
# "BACKEND": "channels_redis.core.RedisChannelLayer",
# "hosts": [("localhost", 6379)],
# 'ROUTING': 'Tetris.routing.channel_routing',
CHANNEL_LAYERS = {
	"default": {
		"BACKEND": "channels_redis.core.RedisChannelLayer",
		"CONFIG": {
			"hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
		},

		# 'ROUTING': 'Tetris.routing.channel_routing',
	},
}

#PROJECT_ROOT = os.path.join(os.path.abspath(__file__))
#STATIC_ROOT = os.path.join(PROJECT_ROOT, '/Main/static/')

#STATICFILES_DIRS = [
#    os.path.join(PROJECT_ROOT, 'static'),
#]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

import dj_database_url
prod_db  =  dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(prod_db)

django_heroku.settings(locals())
